### ISSUE TITLE
The code generator fails to generate valid code for `plan_modifiers`

### ISSUE THREAD

**Issue by TheNilesh** [hashicorp/terraform-plugin-codegen-framework#115]
### tfplugingen-framework CLI version

tfplugingen-framework module: v0.3.1

### Provider Code Spec File

```JSON
{
  "provider": {
    "name": "hashibug",
    "schema": {
      "attributes": [
        {
          "name": "server",
          "string": {
            "optional_required": "optional",
            "description": "API server"
          }
        }
      ]
    }
  },
  "resources": [
    {
      "name": "myresource",
      "schema": {
        "attributes": [
          {
            "name": "id",
            "string": {
              "computed_optional_required": "computed",
              "description": "The id of the resource.",
              "plan_modifiers": [
                {
                  "use_state_for_unknown": {}
                }
              ]
            }
          }
        ]
      }
    }
  ],
  "datasources": [],
  "version": "0.1"
}
```

### Expected Behavior

For the `id` field generated code to be similar to [this](https://developer.hashicorp.com/terraform/tutorials/providers-plugin-framework/providers-plugin-framework-resource-update#enhance-plan-output)

Imports:

```go
  "github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
  "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
```

And the generated schema function should be:

```go
func MyresourceSchema(ctx context.Context) schema.Schema {
  return schema.Schema{
    Attributes: map[string]schema.Attribute{
      "id": schema.StringAttribute{
        Computed:            true,
        Description:         "The id of the resource.",
        MarkdownDescription: "The id of the resource.",
        PlanModifiers:       []planmodifier.String{
          stringplanmodifier.UseStateForUnknown(),
        },
      },
    },
  }
}
```

### Actual Behavior

The generated code does not generate import statements. Hence the IDE complains: `planmodifier` is undefined.

```go
func MyresourceSchema(ctx context.Context) schema.Schema {
  return schema.Schema{
    Attributes: map[string]schema.Attribute{
      "id": schema.StringAttribute{
        Computed:            true,
        Description:         "The id of the resource.",
        MarkdownDescription: "The id of the resource.",
        PlanModifiers:       []planmodifier.String{},
      },
    },
  }
}
```

### Additional Information

The schema is available at https://github.com/hashicorp/terraform-plugin-codegen-spec/blob/main/spec/v0.1/schema.json#L3589

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by TheNilesh** [comment]
@bendbennett Is this under development?

**Comment by bendbennett** [comment]
Hi @TheNilesh 👋 

Sorry you ran into trouble here.

The processing of plan modifiers specified with `requires_replace`, or `use_state_for_unknown` is currently under development/review. In the meanwhile, you should be able to achieve the desired outcome by modifying your spec file,

Replace the following:

```json
              "plan_modifiers": [
                {
                  "use_state_for_unknown": {}
                }
              ]
```

Replace with:

```json
              "plan_modifiers": [
                {
                  "custom": {
                    "imports": [
                      {
                        "path": "github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
                      }
                    ],
                    "schema_definition": "stringplanmodifier.UseStateForUnknown()"
                  }
                }
              ]
```

I will discuss handling of `requires_replace`, or `use_state_for_unknown` with the team and provide further feedback.

**Comment by bendbennett** [comment]
References:

- https://github.com/hashicorp/terraform-plugin-codegen-spec/pull/84
- https://github.com/hashicorp/terraform-plugin-codegen-spec/issues/85
- https://github.com/hashicorp/terraform-plugin-codegen-framework/issues/116

A [PR](https://github.com/hashicorp/terraform-plugin-codegen-spec/pull/84) has been opened to remove Framework-specific implementation details from the codegen-spec schema.

Issues have been opened on [codegen-spec](https://github.com/hashicorp/terraform-plugin-codegen-spec/issues/85), and [codegen-framework ](https://github.com/hashicorp/terraform-plugin-codegen-framework/issues/116)to consider inclusion, and handling of Terraform-specific behaviour properties, respectively.
