### ISSUE TITLE
Potential issue with M2 Max chip

### ISSUE THREAD

**Issue by wesleymccollam** [hashicorp/terraform-plugin-codegen-framework#91]
After running `go install github.com/hashicorp/terraform-plugin-codegen-framework/cmd/tfplugingen-framework@latest` and successful install, I received `command not found: tfplugingen-framework`

**Comment by austinvalle** [comment]
Hey there @wesleymccollam 👋🏻 ,

This sounds like a possible Go environment problem. The `go install` command will build the `tfplugingen-framework` binary and then move it to your `GOPATH` under the `bin` folder. Typically when you install Go, the `GOPATH/bin` folder is added to your `PATH` environment variable so when you run commands in the shell it can find these `go install`'d binaries.

I'd first check what your GOPATH is with `go env GOPATH` and then ensure that this is in your `$PATH` environment variable. Here's some tests from my machine that might help expand (I'm on an M1 mac, Sonoma):

```bash
 $ go version
go version go1.21.1 darwin/arm64

 $ go env GOPATH
/Users/austin.valle/go

 $ echo $PATH | grep /Users/austin.valle/go
<a/bunch/of/other/paths>:/Users/austin.valle/go/bin

 $ go install github.com/hashicorp/terraform-plugin-codegen-framework/cmd/tfplugingen-framework@latest
go: downloading github.com/hashicorp/terraform-plugin-codegen-framework v0.3.0
go: downloading github.com/hashicorp/terraform-plugin-codegen-spec v0.1.1-0.20231024091233-c659ac8a54fc
go: downloading github.com/mattn/go-isatty v0.0.20
go: downloading github.com/Masterminds/semver/v3 v3.2.1
go: downloading github.com/google/uuid v1.4.0
go: downloading github.com/imdario/mergo v0.3.16
go: downloading github.com/spf13/cast v1.5.1
go: downloading github.com/vmihailenco/msgpack/v5 v5.4.1
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20190905194746-02993c407bfb

 $ which tfplugingen-framework
/Users/austin.valle/go/bin/tfplugingen-framework

 $ tfplugingen-framework --version
tfplugingen-framework module: v0.3.0
```

**Comment by wesleymccollam** [comment]
@austinvalle thank you for these troubleshooting steps! This step specifically solved my issue: 
`PATH=$PATH:/Users/wesleymccollam/go/bin`

**Comment by austinvalle** [comment]
Ah, good to hear you figured it out! I manage my Go install with homebrew and forgot that I set that PATH in my `.zshrc` file 😄 

```bash
 $ tail -1 ~/.zshrc
export PATH=$PATH:/Users/austin.valle/go/bin%
```
